kind: pipeline
name: Container Test Application

steps:
- name: Static Analysis
  image: python:3.8-slim
  commands:
  - pip3 install -r reqs/analysis.txt
  - python3 -m isort src
  - python3 -m black src --line-length=79
  - python3 -m flake8 src --verbose

- name: Testing
  image: python:3.8-slim
  commands:
  - pip3 install -r reqs/testing.txt
  - cd src && python3 -m pytest tests/

- name: Build & Push
  image: plugins/docker
  settings:
    repo: USER/IMAGE
    dockerfile: Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    branch:
    - main
    event:
    - push
